# Model architecture parameters
_target_: "NeuroGNN"
distance_csv_root: ${dataset.distance_csv_root}
distance_csv_path: ${dataset.distances_set}
max_epochs: ${train.max_epochs}


# scheduler:
#   step_size: 10
#   gamma: 0.1

# real new ones!
num_nodes: 19     # Number of nodes in graph.
rnn_units: 64     # Number of hidden units in DCRNN. TODO not used!
input_dim: 100 #125    # Input seq feature dim.
gnn_type: "gcn"   # TODO maybe not important?
max_seq_len: 12   # Maximum sequence length in seconds.
dropout: 0.0      # Dropout rate for dropout layer before final FC.


optimizer:
  lr: 1e-4
  l2_wd: 5e-4

# python train.py 
# --input_dir <resampled-dir> 
# --raw_data_dir <tusz-data-dir> 
# --save_dir <save-dir> 
# --max_seq_len <clip-len> 
# --do_train 
# --num_epochs 100 
# --task detection 
# --metric_name auroc 
# --use_fft 
# --lr_init 1e-4 
# --num_classes 1 
# --data_augment 
# --model_name neurognn
