# python ./data/preprocess_detection.py 
# --resampled_dir <resampled-dir> 
# --raw_data_dir <tusz-data-dir> 
# --output_dir <preproc-dir> 
# --clip_len <clip-len> 
# --time_step_size 1 
# --is_fft

steps:
  - _target_: neuro_filter
    fs: 250
    resampleFS: 250
    time_step_size: 1 # Time step size in seconds.
    clip_len: 12      # EEG clip length in seconds.