defaults:
  - preprocessing: fft_bandpass_transformer
  - model: eeg_transformer
  - dataset: temple_dataset
  - _self_

# Training settings
train:
  max_epochs: 1000
  batch_size: 40 #Original 1048
  seed: 20010508
  prefetch_dataset: False # If you have enough ram you can switch to true
  gradient_clip_val: 0.5
  comp_mode: False

# Early stopping
early_stopping:
  monitor: "val_loss"
  monitor_comp_mode: "train_loss"
  patience: 25 #50

# Checkpointing
checkpoint:
  monitor: "val_loss"
  monitor_comp_mode: "train_loss"
  save_top_k: 1
