defaults:
  - preprocessing: fft_gnn
  # - preprocessing: github_filter
  - model: eeg_gnn
  - _self_

dataset:
  data_path: "/home/veit/Uni/Lausanne/NML/EPFL-NWML-25/content/networkML"
  train_set: "train/train"
  test_set: "test/test"
  distance_csv_root: "/home/veit/Uni/Lausanne/NML/EPFL-NWML-25"
  distances_set: "distances_3d.csv"

# Training settings
train:
  max_epochs: 100
  batch_size: 40 #Original 1048
  seed: 2001
  prefetch_dataset: False # If you have enough ram you can switch to true
  gradient_clip_val: 0.5
  comp_mode: False

# Early stopping
early_stopping:
  monitor: "val_loss"
  monitor_comp_mode: "train_loss"
  patience: 50

# Checkpointing
checkpoint:
  monitor: "val_loss"
  monitor_comp_mode: "train_loss"
  save_top_k: 1
