defaults:
  - preprocessing: fft_filter
  - model: gcn_conv
  - dataset: temple_dataset 
  - _self_

# Training settings
train:
  max_epochs: 1000
  batch_size: 40 #Original 1048
  seed: 42
  prefetch_dataset: False # If you have enough ram you can switch to true
  gradient_clip_val: 0.5
  comp_mode: False

# Early stopping
early_stopping:
  monitor: "val_loss"
  monitor_comp_mode: "train_loss"
  patience: 50

# Checkpointing
checkpoint:
  monitor: "val_loss"
  monitor_comp_mode: "train_loss"
  save_top_k: 1
