defaults:
  - _self_
  - eeg_transformer

hydra:
  sweeper:
    params:
      model.eegnet_kernel_size: 64
      model.F1: 128
  sweep:
    dir: multirun_logs/${hydra.job.override_dirname}
    subdir: ${hydra.job.num}